apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  labels:
    app: netflix-app
spec:
  type: ClusterIP
  selector:
    app: netflix-app
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113