apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: netflix-app
  endpoints:
    - port: metrics
      interval: 15s
